### ISSUE TITLE
Problem with running kafkawize jar

### ISSUE THREAD

**Issue by chromy96** [muralibasani/kafkawize#13]
I've followed the instructions from: https://kafkawize.readthedocs.io/en/latest/getting_started.html
but I got stuck at build step (https://kafkawize.readthedocs.io/en/latest/getting_started.html#build).

When I try to run kafkawize using provided command I get the following exception:
` java.io.FileNotFoundException: class path resource [application.properties] cannot be opened because it does not exist`

i've also tried building kafkawize with local profile, but that didn't help.

Could you help me understand what I'm doing wrong?

Additional note: The command in documentation is missing `-D` before spring.config.location :
`java -jar spring.config.location=classpath:/application.properties -Dspring.profiles.active=[local/test/prod] kafkawize-web-3.2.jar`

**Comment by muralibasani** [comment]
Hi chromy, good you mentioned. There is an application properties missing in the resources dir kafkawize-web\src\main\resources, and spring expects a property file there and to while running with java -jar command, we can override with -Dspring.config.location.

You can fix it at your end in 2 ways
1. placing a empty file with name application.properties in kafkawize-web\src\main\resources and rebuild and run with java -jar and the config location for application.properties like below.

java -Dspring.config.location=C:/path/application.properties -jar kafkawize-web/target/kafkawize-web-3.2.jar

2. Place the correct application properties in kafkawize-web\src\main\resources and run 

java -jar kafkawize-web/target/kafkawize-web-3.2.jar

I will fix this in my next release too, and may be remove the modules and keep it simple.

**Comment by muralibasani** [comment]
Hoping it worked. Closing it.
