### ISSUE TITLE
Funtions Missing

### ISSUE THREAD

**Issue by macteja** [muralibasani/kafkawize#15]
Hi Murali,

Thanks for sharing the information, It is really help full.
I have downloaded the latest kafkawize-master zip and opened in IDG, after the I could see functions missing errors. samples are getContactperson, getTeammail, getTrustStoreLocation..etc.

So here we have to add all these functions?

Please help me on resolving the issue.

Thanks,
Mac.

**Comment by muralibasani** [comment]
Hi, seems like you are missing the Lombok plugin in your ide.

**Comment by macteja** [comment]
Thank you Murali.
After Lombok installation it is working fine.

**Comment by macteja** [comment]
Issue resolved closing the same.
