### ISSUE TITLE
support jdbc datastores ?

### ISSUE THREAD

**Issue by jorgheymans** [muralibasani/kafkawize#4]
Is it on the roadmap to support more 'conventional' stores like for example jdbc or even flat file ? This would simplify the deployment a lot.

**Comment by muralibasani** [comment]
Thanks for the issue. Its good to have it. I will add to the roadmap. Please feel free to contribute if you like to for this change.

**Comment by jorgheymans** [comment]
it would be best if you first add a repository abstraction, so the jdbc operations would just be another interface to implement.

**Comment by muralibasani** [comment]
Will do. Thx.

**Comment by muralibasani** [comment]
@jorgheymans , I have updated code (master) with a place holder for jdbc. Would you like to check?

**Comment by muralibasani** [comment]
@jorgheymans I am working on https://github.com/muralibasani/kafkawize/tree/jdbc_support Hopefully will release soon.

**Comment by muralibasani** [comment]
This change is now release in 2.0 version.
