### ISSUE TITLE
Assertion language needing update in UsersTeamsControllerIT.deleteTeamFailure() please

### ISSUE THREAD

**Issue by AndrewJSel** [muralibasani/kafkawize#40]
Got the following on mvn clean install:

[ERROR] Failures: 
[ERROR]   UsersTeamsControllerIT.deleteTeamFailure:256 
Expected: a string containing "Not allowed to delete this team"
     but: was "{"result":"Team cannot be deleted."}"
[INFO] 
[ERROR] Tests run: 45, Failures: 1, Errors: 0, Skipped: 0

Updating the assertion language in UsersTeamsControllerIT.deleteTeamFailure() fixed this for me.

**Comment by muralibasani** [comment]
Commented the assertion for now. Need to take another look on the order of execution.
