### ISSUE TITLE
Compare two Environments(Dev, Stage) and sync the missing TOPIC's, ACL and configurations

### ISSUE THREAD

**Issue by VinodKsheersagar** [muralibasani/kafkawize#6]
Hi Murali,

It would be really great to have an option to compare two different environments(Dev, Stage, PreProd) and highlight the differences and provide an option to sync the missing TOPIC's, ACL  and other Kafka Cluster configurations.

**Comment by muralibasani** [comment]
Thank you @VinodKsheersagar . It's a good feature to show differences but syncing has few complications. I will update Wiki Roadmap and keep you updated.
